name: B2B Marketplace CI


on:
  push:
    branches:
      - main
      - develop

  pull_request:


jobs:

#################################################
# BUILD JOB
#################################################

  build:

    name: Build Application

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      #################################
      # Backend Build
      #################################

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json


      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci


      - name: Build Backend
        working-directory: backend
        run: npm run build



      #################################
      # Flutter Build
      #################################

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable


      - name: Install Flutter Dependencies
        working-directory: mobile
        run: flutter pub get


      - name: Build Flutter Web
        working-directory: mobile
        run: flutter build web --release



      #################################
      # Docker Build
      #################################

      - name: Build Docker Images
        run: docker compose build



#################################################
# TEST JOB
#################################################

  test:

    name: Run Tests

    runs-on: ubuntu-latest

    needs: build


    steps:

      - name: Checkout
        uses: actions/checkout@v4



      #################################
      # Backend Test
      #################################

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json


      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci


      - name: Run Backend Tests
        working-directory: backend
        run: npm test -- --passWithNoTests



      #################################
      # Flutter Test
      #################################

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable


      - name: Flutter Dependencies
        working-directory: mobile
        run: flutter pub get


      - name: Flutter Analyze
        working-directory: mobile
        run: flutter analyze



      #################################
      # Docker Compose Test
      #################################

      - name: Start Containers

        run: docker compose up -d


      - name: Check Containers

        run: docker ps



      - name: Backend Health Check

        run: |

          sleep 10

          curl http://localhost:3000



      - name: Stop Containers

        if: always()

        run: docker compose down -v

  #################################################
  # TEST JOB
  #################################################
  deploy:
    name: Deploy to DigitalOcean

    runs-on: ubuntu-latest

    needs: test

    if: github.ref == 'refs/heads/main'

    steps:

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}

          script: |
            cd ~/projects/B2B-Marketplace

            git pull origin main

            docker compose down

            docker compose up -d --build

            docker image prune -f